/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Dialog: typeof import('./src/components/Dialog')['default']
  const Fragment: typeof import('tsx-dom')['Fragment']
  const components: typeof import('./src/components/index')['components']
  const h: typeof import('tsx-dom')['h']
  const mount: typeof import('./src/components/index')['mount']
  const setupCounter: typeof import('./src/counter')['setupCounter']
}
