/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Fragment: typeof import('start-dom-jsx')['Fragment']
  const coins: typeof import('./src/components/icons/coins')['default']
  const h: typeof import('start-dom-jsx')['h']
  const mount: typeof import('./src/components/index')['mount']
  const setupCounter: typeof import('./src/counter')['setupCounter']
}
